// import React from "react";

// function Product() {
//   const amount = 500; // Amount in INR
//   const currency = "INR";
//   const receiptId = "qwsaq1"; // Unique receipt ID

//   const paymentHandler = async (e) => {
//     e.preventDefault(); // Prevent default form submission behavior

//     try {
//       // Step 1: Create a Razorpay order
//       const response = await fetch("http://localhost:5000/orders", {
//         method: "POST",
//         body: JSON.stringify({
//           amount: amount * 100, // Convert to paise
//           currency,
//           receipt: receiptId,
//         }),
//         headers: {
//           "Content-Type": "application/json",
//         },
//       });

//       const order = await response.json();
//       console.log("Order created:", order);

//       if (!order.id) {
//         throw new Error("Failed to create Razorpay order");
//       }

//       // Step 2: Initialize Razorpay payment
//       const options = {
//         key: "rzp_test_OaZFgQnMYQ9Gmd", // Replace with your Razorpay Key ID
//         amount, // Amount in paise
//         currency,
//         name: "Acme Corp",
//         description: "Test Transaction",
//         image: "https://example.com/your_logo", // Replace with your logo URL
//         order_id: order.id, // Use the order ID generated by Razorpay
//         handler: function (response) {
//           alert(
//             `Payment successful! Payment ID: ${response.razorpay_payment_id}`
//           );
//           alert(`Order ID: ${response.razorpay_order_id}`);
//           alert(`Signature: ${response.razorpay_signature}`);
//           // You can redirect the user or update the UI here
//         },
//         prefill: {
//           name: "Gaurav Kumar",
//           email: "gaurav.kumar@example.com",
//           contact: "9000000000",
//         },
//         notes: {
//           address: "Razorpay Corporate Office",
//         },
//         theme: {
//           color: "#3399cc",
//         },
//       };

//       const rzp1 = new window.Razorpay(options);

//       //   rzp1.on("payment.failed", function (response) {
//       //     alert(`Payment failed: ${response.error.description}`);
//       //     console.error("Payment failed response:", response);
//       //   });

//       rzp1.open();
//     } catch (error) {
//       console.error("Error during payment process:", error);
//       alert("Payment failed. Please try again.");
//     }
//   };

//   return (
//     <div className="product">
//       <h2>T-Shirt</h2>
//       <button onClick={paymentHandler}>Pay ₹{amount}</button>
//     </div>
//   );
// }

// export default Product;
